export const ERROR_CODES = {
  NOT_FOUND: 'COUNTER.NOT_FOUND',
  LIMIT_REACHED: 'COUNTER.LIMIT_REACHED',
  INVALID_NAME: 'COUNTER.INVALID_NAME',
  NAME_INVALID_LENGTH: 'COUNTER.NAME_INVALID_LENGTH',
}

export const MUTATIONS = {
  ADD_COUNTER: 'ADD_COUNTER',
  REMOVE_COUNTER: 'REMOVE_COUNTER',
  UPDATE_COUNTER_VALUE: 'UPDATE_COUNTER_VALUE',
  UPDATE_SORTING: 'UPDATE_SORTING',
  UPDATE_FILTERS: 'UPDATE_FILTERS',
  REPLACE_COUNTERS: 'REPLACE_COUNTERS',
}

export const SORT_OPTIONS = {
  BY: {
    NAME: 'COUNTER.NAME',
    VALUE: 'COUNTER.VALUE',
  },
  ORDER: {
    ASC: 'COUNTER.ASC',
    DESC: 'COUNTER.DESC',
  },
}

export const FILTER_OPTIONS = {
  BY: {
    NONE: null,
    GREATER_THAN: 'COUNTER.GREATER_THAN',
    LESS_THAN: 'COUNTER.LESS_THAN',
  },
}
